INPUT_CHANNEL = "INPUT_STREAM_DATA"
SAMPLE_FILE = "data/sorted_file.csv"
TEST_FILE = "data/train_sample.csv"
TRAIN_FILE = "data/train.csv"
BLOOM_FILTER_KEY = "bloom"
DUPLICATE_COUNT_KEY = "duplicates"
HASHKEY_LOOKUP_KEY = "clickevents"
HASHKEY_DUP_KEY = "dupclickevent"